name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        version: [0.5.1, 0.6.3, 0.7.4]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install asdf
        run: |
          git clone https://github.com/asdf-vm/asdf.git $HOME/asdf
      - name: Test the plugin
        run: |
          . $HOME/asdf/asdf.sh
          asdf plugin-test zola $GITHUB_WORKSPACE 'zola --version' --asdf-tool-version ${{matrix.version}} 
